document.getElementById('resultForm').addEventListener('submit', function(e) {
    e.preventDefault();

    const classSelected = document.getElementById('class').value;
    const rollNumber = document.getElementById('rollNumber').value;
    
    if (classSelected && rollNumber) {
        fetchResult(classSelected, rollNumber);
    } else {
        alert("Please select a class and enter a roll number.");
    }
});

function fetchResult(classSelected, rollNumber) {
    fetch('https://www.knarlix.free.nf/Test/Result.json')
        .then(response => response.json())
        .then(data => {
            const classData = data[classSelected];
            const student = classData.find(student => student.roll_number === rollNumber);
            
            if (student) {
                displayResult(student);
                generatePDF(student);
            } else {
                alert("No data found for the given roll number.");
            }
        });
}

function displayResult(student) {
    const resultDiv = document.getElementById('resultData');
    resultDiv.style.display = 'block';
    resultDiv.innerHTML = `
        <h2>Result</h2>
        <p><strong>Name:</strong> ${student.name}</p>
        <p><strong>Roll Number:</strong> ${student.roll_number}</p>
        <p><strong>Total Marks:</strong> ${student.total_marks}</p>
        <p><strong>Status:</strong> ${student.result_status}</p>
    `;
}

function generatePDF(student) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    const logoUrl = "https://www.knarlix.free.nf/images/pfp.png";

    // Load and add logo
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.src = logoUrl;
    img.onload = () => {
        doc.setFillColor(245, 245, 245);
        doc.rect(0, 0, 210, 297, 'F'); // Light background

        // Add funky header background
        doc.setFillColor(0, 153, 255);
        doc.roundedRect(10, 10, 190, 30, 5, 5, 'F');

        doc.addImage(img, 'PNG', 15, 12, 25, 25);

        doc.setFontSize(22);
        doc.setTextColor(255, 255, 255);
        doc.setFont("helvetica", "bold");
        doc.text("KnarliX Student Result", 45, 30);

        // Draw data box
        doc.setFillColor(255, 255, 255);
        doc.setDrawColor(0, 153, 255);
        doc.roundedRect(20, 50, 170, 120, 5, 5, 'FD');

        // Labels and values
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(16);
        doc.setFont("helvetica", "normal");

        const info = [
            { label: "Name", value: student.name },
            { label: "Roll Number", value: student.roll_number },
            { label: "Total Marks", value: student.total_marks },
            { label: "Result Status", value: student.result_status }
        ];

        let y = 70;
        info.forEach(item => {
            doc.setFont("helvetica", "bold");
            doc.setTextColor(50, 50, 50);
            doc.text(`${item.label}:`, 30, y);

            doc.setFont("helvetica", "normal");
            doc.setTextColor(80, 80, 255);
            doc.text(`${item.value}`, 90, y);
            y += 25;
        });

        // Footer
        doc.setTextColor(100);
        doc.setFontSize(12);
        doc.setFont("courier", "italic");
        doc.text("Generated by KnarliX Portal", 65, 190);
        doc.text("www.knarlix.free.nf", 75, 200);

        // Save it
        doc.save(`${student.name}_Result.pdf`);
    };
}
